# Plugin developed by GFelberg
# Config translated by GLOBEsg
# Config.yml

# language: en
# Thanks for downloading my plugin. For more plugins, don't forget to look my updates!
# If you find any bugs or ideas to the plugin, pm me at spigot.

# language: br/pt
# Obrigado por baixar meu plugin. Para mais plugins, não esqueça de olhar as atualizações!
# Se você encontrar algum problema ou ter alguma ideia para o plugin, pm no spigot.

# Permissions

# back.back : Access to Back command
# back.bypass : Access to Back command without cooldown
# back.bypass.economy : Access to Back command without withdraw money
# back.admin : Access to the Admin Help and List all Blocked Worlds
# back.update : Access to receive notifications about the plugin, as new versions
# back.reload : Access to Reload the Plugin

# Placeholders

# %back_prefix% : Gets the Back prefix
# %back_delaytime% : Gets the remaining time for use the Back Command, if cooldown is enabled.
# %back_cost% : Gets the teleport cost
# %back_withdraw% : Gets the money taken from the player account

# Update-Check Option - https://www.spigotmc.org/resources/back.94702/
# If true, a permission will be required to receive the notifications if the player doesn't have the OP enabled
update-check: true

# Warning: The "death_locations" file SHOULD NOT be touched. The file works itself with the configurations and
# deaths in the server.

# Configuration 1.0
# This configuration will display the Back Messages
Back:
  Prefix: "&b[&eBack&b]&r"
  Message: "&e你已经传送到你最新的死亡点"
  Failed: "&c你的传送失败了，无法找到最新的死亡点！"
  BlockedWorld: "&c你的死亡点在被管理员禁用命令的世界里！"
  NoPermission: "&c你没有运行这条指令的权限！"

# Configuration 1.1
# This configuration will display the Help Page Messages
Help:
  Page: "&e展示此页"
  Back: "&e传送到你最新的死亡点"
  Backlist: "&e列出所有禁用的世界"
  Reload: "&e重载本插件"

# Configuration 1.2
# This configuration will display the Cooldown System

# If "true", the player will have to wait 'x' seconds to use the command after his death.

# If "false", the player can use the command immediately after his death.

# If the player has "back.bypass" permission, the player will be able to use the command even with the cooldown enabled.
# By default, the cooldown is disabled.

# The Delay message is "You must wait 'x' seconds to use the command!", which 'x' is the %back_delaytime% placeholder.

Cooldown:
  Enable: false
  Message: "&c你必须等待 &b%back_delaytime% &c秒才能使用这个指令！"
  Time: 10

# Configuration 1.3
# This configuration will display the ClickOption System (Server Version = 1.16+)

# By default, you can see there's a space above and under the "&c[Click here to Death Location]" here in config.yml.
# However, in game, it's 2 spaces above and under (1 space above and under by default in game (can't be changed) + spaces in config.yml).

# If you believe is a lot, you can't just remove the spaces here in the config.yml, so only 1 space will be visible above and under in game.
# If you want to add more information, you can change or add more lines.

# This option can be only be enabled if your server version is 1.16 or above. If the option is
# activated and your server is below 1.16, some logs will be sent into the Console each time
# the command is used. To stop, disable the option and use the /back reload

# For a better explanation, please check the Back Overview Page at spigot: https://www.spigotmc.org/resources/back.94702/
ClickOptionEnable: false

# Messages displayed in game
ClickOption:
  - ""
  - "#FF5555[Click here to Death Location]"
  - ""

# Configuration 1.4
# This configuration will display the WorldBlacklist System

# WorldBlacklist is a method created to block the /back command to be executed. If you put a world that exists in your server in the list, if a player dies and execute the command
# the player will be blocked. The command will only works if he dies inside an allowed world.

# By default, this option will be disabled.
WorldBlacklist:
  Enable: false
  Title: "&b屏蔽的世界"

# Blocked Worlds
BlockedWorlds:
  - 'world1'
  - 'world2'
  - 'world3'

# Configuration 1.5
# This configuration will display the Vault System

# You must have the Vault and an Economy Plugin to the Vault System works. If you don't have one of them, the default
# method will be applied, which is the classic mode.

# If the player has "back.bypass.economy" permission, the player will be able to use the command without withdraw money
# if Vault System is enabled.

Vault:
  Enable: false
  TeleportCost: 10
  Withdraw: "&e$%back_withdraw% &b在你的账号被移出了"
  NoMoney: "&c你需要 $%back_cost% 来传送！"
